sudo: required

language: php

php:
  - 7.4

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

install:
  - travis_retry composer update --prefer-source
script:
  - vendor/bin/phpunit

branches:
  only:
    - master
